### ISSUE TITLE
Links to add

### ISSUE THREAD

**Issue by lassik** [schemeorg/standards.scheme.org#1]
RnRS authors' mailing list
http://www.swiss.ai.mit.edu/projects/scheme/rrrs-archive.html

http://www.r6rs.org/
http://www.r6rs.org/r6rs-editors/
http://www.r6rs.org/process.html

**Comment by lassik** [comment]
The above are all the RnRS links from schemers.org that standards.scheme.org does not yet have.

**Comment by arthurgleckler** [comment]
On Fri, Jan 1, 2021 at 5:43 PM Lassi Kortela <notifications@github.com>
wrote:

> The above are all the RnRS links from schemers.org that
> standards.scheme.org does not yet have.
>
Thanks.  I added those, made some other edits, and pushed the result.
